import type { Metadata } from "next";
import "./globals.css";
import {Roboto_Slab}  from "next/font/google"
import MainLayout from "@/components/layout/MainLayout";
import ReduxProvider from "@/redux/ReduxProvider";

export const roboto_slab = Roboto_Slab({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto_slab.className}>
     <ReduxProvider>
     <body>
        <MainLayout>
        {children}
        </MainLayout>
      </body>
     </ReduxProvider>
    </html>
  );
}
